version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      host: localhost
      MYSQL_DATABASE: urls
      MYSQL_USER: sampath
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-data:
